// llvm2-lower/adapter.rs - tMIR to internal LIR adapter layer
//
// Author: Andrew Yates <ayates@dropbox.com>
// Copyright 2026 Dropbox, Inc. | License: Apache-2.0
//
// Reference: designs/2026-04-13-tmir-integration.md (adapter layer architecture)
//
// Translates tMIR (the universal IR from tRust/tSwift/tC) to the internal LIR
// consumed by the ISel. This adapter approach (Option A in the design doc)
// decouples the ISel from tMIR API changes while preserving proof annotations
// as metadata for downstream optimization passes.

//! tMIR to internal LIR adapter layer.
//!
//! This module translates `tmir_func::Module` / `tmir_func::Function` into the
//! internal `llvm2_lower::function::Function` representation, mapping each tMIR
//! instruction to one or more internal `Instruction`s.
//!
//! Proof annotations from tMIR are extracted into a `ProofContext` for consumption
//! by downstream optimization passes (llvm2-opt).

use std::collections::HashMap;

use tmir_func::{Block as TmirBlock, Function as TmirFunction, Module as TmirModule};
use tmir_instrs::{BinOp, CastOp, CmpOp, Instr, InstrNode, UnOp};
use tmir_types::{BlockId, FuncId, StructDef, Ty, ValueId};

use crate::function::{BasicBlock, Function, Signature};
use crate::instructions::{Block, FloatCC, Instruction, IntCC, Opcode, Value};
use crate::types::Type;

// ---------------------------------------------------------------------------
// Error types
// ---------------------------------------------------------------------------

/// Errors that can occur during tMIR to LIR translation.
#[derive(Debug, Clone, thiserror::Error)]
pub enum AdapterError {
    #[error("unsupported tMIR type: {0}")]
    UnsupportedType(String),

    #[error("void type used as value")]
    VoidValue,

    #[error("instruction has no result but one was expected")]
    MissingResult,

    #[error("unsupported tMIR instruction: {0}")]
    UnsupportedInstruction(String),

    #[error("unknown block reference: BlockId({0})")]
    UnknownBlock(u32),

    #[error("unknown value reference: ValueId({0})")]
    UnknownValue(u32),

    #[error("unsupported integer bit-width: {0}")]
    UnsupportedBitWidth(u16),
}

// ---------------------------------------------------------------------------
// Proof annotations
// ---------------------------------------------------------------------------

/// Proof annotations attached to tMIR values/instructions.
///
/// These proofs are generated by the source-language compiler (tRust, tSwift, tC)
/// and verified by z4. The adapter extracts them for downstream optimization.
#[derive(Debug, Clone, PartialEq)]
pub enum Proof {
    /// Addition/subtraction guaranteed not to overflow.
    /// Enables: skip overflow check, use wrapping arithmetic directly.
    NoOverflow { signed: bool },

    /// Array/pointer access is within bounds.
    /// Enables: skip bounds check, use direct load/store.
    InBounds { base: ValueId, index: ValueId },

    /// Pointer is guaranteed non-null.
    /// Enables: skip null check.
    NotNull { ptr: ValueId },

    /// Borrow is guaranteed valid (lifetime within scope).
    /// Enables: skip liveness check, treat as raw pointer.
    ValidBorrow { borrow: ValueId },

    /// Value is within a specific range [lo, hi].
    /// Enables: range-based optimizations (width narrowing, skip sign extension).
    InRange { lo: i128, hi: i128 },

    /// Division divisor is guaranteed non-zero.
    /// Enables: skip divide-by-zero check.
    NonZeroDivisor { divisor: ValueId },

    /// Shift amount is within [0, bitwidth).
    /// Enables: skip shift-amount masking.
    ValidShift { amount: ValueId, bitwidth: u16 },
}

/// Proof metadata carried through the compilation pipeline.
///
/// After the adapter translates tMIR to internal LIR, proof annotations are
/// re-keyed from `ValueId` to internal `Value` references so downstream
/// passes can query them.
#[derive(Debug, Clone, Default)]
pub struct ProofContext {
    /// Proofs attached to specific internal LIR values (re-keyed from tMIR ValueId).
    pub value_proofs: HashMap<Value, Vec<Proof>>,
}

impl ProofContext {
    /// Check if a value has a specific proof type.
    pub fn has_no_overflow(&self, val: &Value) -> bool {
        self.value_proofs
            .get(val)
            .is_some_and(|proofs| proofs.iter().any(|p| matches!(p, Proof::NoOverflow { .. })))
    }

    /// Check if a value has a non-null proof.
    pub fn has_not_null(&self, val: &Value) -> bool {
        self.value_proofs
            .get(val)
            .is_some_and(|proofs| proofs.iter().any(|p| matches!(p, Proof::NotNull { .. })))
    }

    /// Check if a value has an in-bounds proof.
    pub fn has_in_bounds(&self, val: &Value) -> bool {
        self.value_proofs
            .get(val)
            .is_some_and(|proofs| proofs.iter().any(|p| matches!(p, Proof::InBounds { .. })))
    }

    /// Check if a value has a non-zero divisor proof.
    pub fn has_non_zero_divisor(&self, val: &Value) -> bool {
        self.value_proofs.get(val).is_some_and(|proofs| {
            proofs
                .iter()
                .any(|p| matches!(p, Proof::NonZeroDivisor { .. }))
        })
    }

    /// Get range information for a value, if available.
    pub fn get_range(&self, val: &Value) -> Option<(i128, i128)> {
        self.value_proofs.get(val).and_then(|proofs| {
            proofs.iter().find_map(|p| match p {
                Proof::InRange { lo, hi } => Some((*lo, *hi)),
                _ => None,
            })
        })
    }
}

// ---------------------------------------------------------------------------
// Type translation
// ---------------------------------------------------------------------------

/// Convert a tMIR `Ty` to an internal LIR `Type`.
///
/// Signedness is lost in the conversion (tMIR `Int` vs `UInt` both map to `I*`).
/// The signedness is preserved in the opcodes (e.g., `Sdiv` vs `Udiv`).
pub fn translate_type(ty: &Ty) -> Result<Type, AdapterError> {
    match ty {
        Ty::Bool => Ok(Type::B1),
        Ty::Int(8) | Ty::UInt(8) => Ok(Type::I8),
        Ty::Int(16) | Ty::UInt(16) => Ok(Type::I16),
        Ty::Int(32) | Ty::UInt(32) => Ok(Type::I32),
        Ty::Int(64) | Ty::UInt(64) => Ok(Type::I64),
        Ty::Int(128) | Ty::UInt(128) => Ok(Type::I128),
        Ty::Float(32) => Ok(Type::F32),
        Ty::Float(64) => Ok(Type::F64),
        Ty::Ptr(_) => Ok(Type::I64), // All pointers are 64-bit on AArch64
        Ty::Void => Err(AdapterError::VoidValue),
        Ty::Int(w) | Ty::UInt(w) | Ty::Float(w) => {
            Err(AdapterError::UnsupportedBitWidth(*w))
        }
        Ty::Struct(_) | Ty::Array(_, _) | Ty::Func(_) => {
            Err(AdapterError::UnsupportedType(format!("{:?}", ty)))
        }
    }
}

/// Translate a tMIR function signature to an internal LIR `Signature`.
fn translate_signature(func: &TmirFunction) -> Result<Signature, AdapterError> {
    let params: Vec<Type> = func
        .ty
        .params
        .iter()
        .map(|ty| translate_type(ty))
        .collect::<Result<Vec<_>, _>>()?;
    let returns: Vec<Type> = func
        .ty
        .returns
        .iter()
        .map(|ty| translate_type(ty))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(Signature { params, returns })
}

// ---------------------------------------------------------------------------
// Comparison predicate translation
// ---------------------------------------------------------------------------

/// Map tMIR integer comparison predicates to internal `IntCC`.
fn translate_int_cmp(op: &CmpOp) -> Option<IntCC> {
    match op {
        CmpOp::Eq => Some(IntCC::Equal),
        CmpOp::Ne => Some(IntCC::NotEqual),
        CmpOp::Slt => Some(IntCC::SignedLessThan),
        CmpOp::Sle => Some(IntCC::SignedLessThanOrEqual),
        CmpOp::Sgt => Some(IntCC::SignedGreaterThan),
        CmpOp::Sge => Some(IntCC::SignedGreaterThanOrEqual),
        CmpOp::Ult => Some(IntCC::UnsignedLessThan),
        CmpOp::Ule => Some(IntCC::UnsignedLessThanOrEqual),
        CmpOp::Ugt => Some(IntCC::UnsignedGreaterThan),
        CmpOp::Uge => Some(IntCC::UnsignedGreaterThanOrEqual),
        _ => None, // Float comparisons handled separately
    }
}

/// Map tMIR float comparison predicates to internal `FloatCC`.
fn translate_float_cmp(op: &CmpOp) -> Option<FloatCC> {
    match op {
        CmpOp::FOeq => Some(FloatCC::Equal),
        CmpOp::FOne => Some(FloatCC::NotEqual),
        CmpOp::FOlt => Some(FloatCC::LessThan),
        CmpOp::FOle => Some(FloatCC::LessThanOrEqual),
        CmpOp::FOgt => Some(FloatCC::GreaterThan),
        CmpOp::FOge => Some(FloatCC::GreaterThanOrEqual),
        // Unordered float comparisons: map to closest ordered variant.
        // The ISel will handle the NaN-aware lowering via CSEL chains.
        CmpOp::FUeq => Some(FloatCC::Equal),
        CmpOp::FUne => Some(FloatCC::NotEqual),
        CmpOp::FUlt => Some(FloatCC::LessThan),
        CmpOp::FUle => Some(FloatCC::LessThanOrEqual),
        CmpOp::FUgt => Some(FloatCC::GreaterThan),
        CmpOp::FUge => Some(FloatCC::GreaterThanOrEqual),
        _ => None, // Integer comparisons handled separately
    }
}

// ---------------------------------------------------------------------------
// Adapter state
// ---------------------------------------------------------------------------

/// The tMIR-to-LIR adapter. Translates one function at a time.
struct TmirAdapter<'a> {
    /// Struct definitions from the module (for future aggregate support).
    _structs: &'a [StructDef],

    /// tMIR ValueId -> internal LIR Value mapping.
    value_map: HashMap<ValueId, Value>,

    /// tMIR BlockId -> internal LIR Block mapping.
    block_map: HashMap<BlockId, Block>,

    /// Next internal Value id to allocate.
    next_value: u32,

    /// Next internal Block id to allocate.
    next_block: u32,

    /// Collected proof annotations, keyed by internal Value.
    proof_ctx: ProofContext,

    /// Reference to the tMIR function being translated (for block lookups).
    tmir_func: Option<&'a TmirFunction>,
}

impl<'a> TmirAdapter<'a> {
    fn new(structs: &'a [StructDef]) -> Self {
        Self {
            _structs: structs,
            value_map: HashMap::new(),
            block_map: HashMap::new(),
            next_value: 0,
            next_block: 0,
            proof_ctx: ProofContext::default(),
            tmir_func: None,
        }
    }

    /// Allocate a fresh internal Value.
    fn fresh_value(&mut self) -> Value {
        let v = Value(self.next_value);
        self.next_value += 1;
        v
    }

    /// Map a tMIR ValueId to an internal Value, creating a fresh one if needed.
    fn map_value(&mut self, vid: ValueId) -> Value {
        if let Some(&v) = self.value_map.get(&vid) {
            return v;
        }
        let v = self.fresh_value();
        self.value_map.insert(vid, v);
        v
    }

    /// Map a tMIR BlockId to an internal Block, creating a fresh one if needed.
    fn map_block(&mut self, bid: BlockId) -> Block {
        if let Some(&b) = self.block_map.get(&bid) {
            return b;
        }
        let b = Block(self.next_block);
        self.next_block += 1;
        self.block_map.insert(bid, b);
        b
    }

    /// Get the result Value for an instruction, or error if none.
    fn map_result(&mut self, results: &[ValueId]) -> Result<Value, AdapterError> {
        if results.is_empty() {
            return Err(AdapterError::MissingResult);
        }
        Ok(self.map_value(results[0]))
    }

    /// Map all result Values for an instruction.
    fn map_results(&mut self, results: &[ValueId]) -> Vec<Value> {
        results.iter().map(|vid| self.map_value(*vid)).collect()
    }

    // -----------------------------------------------------------------------
    // Top-level translation
    // -----------------------------------------------------------------------

    /// Translate a tMIR function to an internal LIR Function + ProofContext.
    fn translate(
        &mut self,
        func: &'a TmirFunction,
    ) -> Result<(Function, ProofContext), AdapterError> {
        self.tmir_func = Some(func);

        let sig = translate_signature(func)?;
        let entry = self.map_block(func.entry);

        let mut lir_func = Function::new(func.name.clone(), sig);
        lir_func.entry_block = entry;

        // Translate all blocks.
        for tmir_block in func.iter_blocks() {
            let block_id = self.map_block(tmir_block.id);
            let basic_block = self.translate_block(tmir_block)?;
            lir_func.blocks.insert(block_id, basic_block);
        }

        Ok((lir_func, self.proof_ctx.clone()))
    }

    /// Translate a tMIR basic block.
    fn translate_block(
        &mut self,
        tmir_block: &TmirBlock,
    ) -> Result<BasicBlock, AdapterError> {
        let mut bb = BasicBlock::default();

        // Translate block parameters (phi-like).
        for (vid, ty) in &tmir_block.params {
            let val = self.map_value(*vid);
            let lir_ty = translate_type(ty)?;
            bb.params.push((val, lir_ty));
        }

        // Translate each instruction in the block body.
        for node in &tmir_block.body {
            let instrs = self.translate_instruction(node)?;
            bb.instructions.extend(instrs);
        }

        Ok(bb)
    }

    // -----------------------------------------------------------------------
    // Instruction translation
    // -----------------------------------------------------------------------

    /// Translate a single tMIR instruction node into one or more LIR instructions.
    fn translate_instruction(
        &mut self,
        node: &InstrNode,
    ) -> Result<Vec<Instruction>, AdapterError> {
        match &node.instr {
            Instr::BinOp { op, ty, lhs, rhs } => {
                self.translate_binop(op, ty, lhs, rhs, &node.results)
            }
            Instr::UnOp { op, ty, operand } => {
                self.translate_unop(op, ty, operand, &node.results)
            }
            Instr::Cmp { op, ty, lhs, rhs } => {
                self.translate_cmp(op, ty, lhs, rhs, &node.results)
            }
            Instr::Cast {
                op,
                src_ty,
                dst_ty,
                operand,
            } => self.translate_cast(op, src_ty, dst_ty, operand, &node.results),
            Instr::Load { ty, ptr } => self.translate_load(ty, ptr, &node.results),
            Instr::Store { ty: _, ptr, value } => self.translate_store(ptr, value),
            Instr::Alloc { ty, count } => self.translate_alloc(ty, count, &node.results),
            Instr::Br { target, args } => self.translate_br(target, args),
            Instr::CondBr {
                cond,
                then_target,
                then_args,
                else_target,
                else_args,
            } => self.translate_condbr(cond, then_target, then_args, else_target, else_args),
            Instr::Return { values } => self.translate_return(values),
            Instr::Call {
                func,
                args,
                ret_ty,
            } => self.translate_call(func, args, ret_ty, &node.results),
            Instr::Phi { ty, incoming } => self.translate_phi(ty, incoming, &node.results),
            Instr::Const { ty, value } => self.translate_const(ty, *value, &node.results),
            Instr::FConst { ty, value } => self.translate_fconst(ty, *value, &node.results),
            Instr::Nop => Ok(vec![]),
            // Ownership instructions: lower as no-ops or pointer copies for now.
            Instr::Borrow { ty: _, value } | Instr::BorrowMut { ty: _, value } => {
                // Borrow/BorrowMut: result is a copy of the pointer.
                if node.results.is_empty() {
                    return Ok(vec![]);
                }
                let src = self.map_value(*value);
                let dst = self.map_result(&node.results)?;
                Ok(vec![Instruction {
                    opcode: Opcode::Iadd, // Copy via add-zero pattern (no dedicated Copy opcode yet)
                    args: vec![src],
                    results: vec![dst],
                }])
            }
            Instr::EndBorrow { .. }
            | Instr::Retain { .. }
            | Instr::Release { .. }
            | Instr::Dealloc { .. } => {
                // Void ownership ops: no-op in the LIR for now.
                Ok(vec![])
            }
            Instr::IsUnique { value } => {
                // Lower as a constant true for now (no ARC runtime).
                if node.results.is_empty() {
                    return Ok(vec![]);
                }
                let _ = value;
                let dst = self.map_result(&node.results)?;
                Ok(vec![Instruction {
                    opcode: Opcode::Iconst {
                        ty: Type::B1,
                        imm: 1,
                    },
                    args: vec![],
                    results: vec![dst],
                }])
            }
            // Aggregate operations: unsupported in MVP.
            Instr::Struct { .. } | Instr::Field { .. } | Instr::Index { .. } => {
                Err(AdapterError::UnsupportedInstruction(format!(
                    "{:?}",
                    node.instr
                )))
            }
            // Switch: unsupported in MVP.
            Instr::Switch { .. } => Err(AdapterError::UnsupportedInstruction(
                "Switch".to_string(),
            )),
            // CallIndirect: unsupported in MVP.
            Instr::CallIndirect { .. } => Err(AdapterError::UnsupportedInstruction(
                "CallIndirect".to_string(),
            )),
        }
    }

    // -----------------------------------------------------------------------
    // Binary operations
    // -----------------------------------------------------------------------

    fn translate_binop(
        &mut self,
        op: &BinOp,
        ty: &Ty,
        lhs: &ValueId,
        rhs: &ValueId,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let opcode = match op {
            BinOp::Add => Opcode::Iadd,
            BinOp::Sub => Opcode::Isub,
            BinOp::Mul => Opcode::Imul,
            BinOp::SDiv => Opcode::Sdiv,
            BinOp::UDiv => Opcode::Udiv,
            BinOp::And => Opcode::Band,
            BinOp::Or => Opcode::Bor,
            BinOp::Xor => Opcode::Bxor,
            BinOp::Shl => Opcode::Ishl,
            BinOp::AShr => Opcode::Sshr,
            BinOp::LShr => Opcode::Ushr,
            BinOp::FAdd => Opcode::Fadd,
            BinOp::FSub => Opcode::Fsub,
            BinOp::FMul => Opcode::Fmul,
            BinOp::FDiv => Opcode::Fdiv,
            // Remainder: AArch64 has no remainder instruction.
            // Lower as: result = lhs - (lhs / rhs) * rhs
            BinOp::SRem => return self.translate_remainder(true, ty, lhs, rhs, results),
            BinOp::URem => return self.translate_remainder(false, ty, lhs, rhs, results),
        };

        let lhs_val = self.map_value(*lhs);
        let rhs_val = self.map_value(*rhs);
        let result = self.map_result(results)?;

        Ok(vec![Instruction {
            opcode,
            args: vec![lhs_val, rhs_val],
            results: vec![result],
        }])
    }

    /// Translate remainder (SRem/URem) as a div + mul + sub sequence.
    ///
    /// result = lhs - (lhs / rhs) * rhs
    fn translate_remainder(
        &mut self,
        signed: bool,
        _ty: &Ty,
        lhs: &ValueId,
        rhs: &ValueId,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let lhs_val = self.map_value(*lhs);
        let rhs_val = self.map_value(*rhs);
        let result = self.map_result(results)?;

        let div_opcode = if signed { Opcode::Sdiv } else { Opcode::Udiv };

        // Step 1: quotient = lhs / rhs
        let quotient = self.fresh_value();
        let div_inst = Instruction {
            opcode: div_opcode,
            args: vec![lhs_val, rhs_val],
            results: vec![quotient],
        };

        // Step 2: product = quotient * rhs
        let product = self.fresh_value();
        let mul_inst = Instruction {
            opcode: Opcode::Imul,
            args: vec![quotient, rhs_val],
            results: vec![product],
        };

        // Step 3: result = lhs - product
        let sub_inst = Instruction {
            opcode: Opcode::Isub,
            args: vec![lhs_val, product],
            results: vec![result],
        };

        Ok(vec![div_inst, mul_inst, sub_inst])
    }

    // -----------------------------------------------------------------------
    // Unary operations
    // -----------------------------------------------------------------------

    fn translate_unop(
        &mut self,
        op: &UnOp,
        ty: &Ty,
        operand: &ValueId,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let src = self.map_value(*operand);
        let dst = self.map_result(results)?;

        match op {
            UnOp::Neg => {
                // Neg: result = 0 - operand
                let lir_ty = translate_type(ty)?;
                let zero = self.fresh_value();
                let zero_inst = Instruction {
                    opcode: Opcode::Iconst { ty: lir_ty, imm: 0 },
                    args: vec![],
                    results: vec![zero],
                };
                let sub_inst = Instruction {
                    opcode: Opcode::Isub,
                    args: vec![zero, src],
                    results: vec![dst],
                };
                Ok(vec![zero_inst, sub_inst])
            }
            UnOp::Not => {
                // Bitwise NOT: result = operand XOR -1 (all ones)
                let lir_ty = translate_type(ty)?;
                let all_ones = self.fresh_value();
                let ones_inst = Instruction {
                    opcode: Opcode::Iconst {
                        ty: lir_ty,
                        imm: -1,
                    },
                    args: vec![],
                    results: vec![all_ones],
                };
                let xor_inst = Instruction {
                    opcode: Opcode::Bxor,
                    args: vec![src, all_ones],
                    results: vec![dst],
                };
                Ok(vec![ones_inst, xor_inst])
            }
            UnOp::FNeg => {
                // FNeg: result = 0.0 - operand
                // The ISel should pattern-match this into FNEG.
                let lir_ty = translate_type(ty)?;
                let zero = self.fresh_value();
                let zero_inst = Instruction {
                    opcode: Opcode::Fconst {
                        ty: lir_ty,
                        imm: 0.0,
                    },
                    args: vec![],
                    results: vec![zero],
                };
                let sub_inst = Instruction {
                    opcode: Opcode::Fsub,
                    args: vec![zero, src],
                    results: vec![dst],
                };
                Ok(vec![zero_inst, sub_inst])
            }
        }
    }

    // -----------------------------------------------------------------------
    // Comparisons
    // -----------------------------------------------------------------------

    fn translate_cmp(
        &mut self,
        op: &CmpOp,
        ty: &Ty,
        lhs: &ValueId,
        rhs: &ValueId,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let lhs_val = self.map_value(*lhs);
        let rhs_val = self.map_value(*rhs);
        let result = self.map_result(results)?;

        // Determine if this is an integer or float comparison.
        if ty.is_float() {
            let cond = translate_float_cmp(op).ok_or_else(|| {
                AdapterError::UnsupportedInstruction(format!("float cmp {:?}", op))
            })?;
            Ok(vec![Instruction {
                opcode: Opcode::Fcmp { cond },
                args: vec![lhs_val, rhs_val],
                results: vec![result],
            }])
        } else {
            let cond = translate_int_cmp(op).ok_or_else(|| {
                AdapterError::UnsupportedInstruction(format!("int cmp {:?}", op))
            })?;
            Ok(vec![Instruction {
                opcode: Opcode::Icmp { cond },
                args: vec![lhs_val, rhs_val],
                results: vec![result],
            }])
        }
    }

    // -----------------------------------------------------------------------
    // Cast operations
    // -----------------------------------------------------------------------

    fn translate_cast(
        &mut self,
        op: &CastOp,
        src_ty: &Ty,
        dst_ty: &Ty,
        operand: &ValueId,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let src = self.map_value(*operand);
        let dst = self.map_result(results)?;
        let from = translate_type(src_ty)?;
        let to = translate_type(dst_ty)?;

        let opcode = match op {
            CastOp::SExt => Opcode::Sextend {
                from_ty: from,
                to_ty: to,
            },
            CastOp::ZExt => Opcode::Uextend {
                from_ty: from,
                to_ty: to,
            },
            CastOp::Trunc => {
                // Truncation: use Uextend with swapped semantics
                // (the ISel will emit AND with a mask or MOV W-reg).
                // For now, emit as Uextend from larger to smaller, which
                // the ISel can pattern-match. The to_ty is smaller.
                Opcode::Uextend {
                    from_ty: from,
                    to_ty: to,
                }
            }
            CastOp::FPToSI => Opcode::FcvtToInt { dst_ty: to },
            CastOp::FPToUI => {
                // Unsigned float-to-int: use FcvtToInt (ISel needs to emit FCVTZU).
                Opcode::FcvtToInt { dst_ty: to }
            }
            CastOp::SIToFP | CastOp::UIToFP => Opcode::FcvtFromInt { src_ty: from },
            CastOp::FPExt | CastOp::FPTrunc => {
                // Float precision conversion: map to FcvtFromInt/FcvtToInt pattern.
                // This is a simplification; a dedicated opcode would be better.
                Opcode::FcvtFromInt { src_ty: from }
            }
            CastOp::PtrToInt | CastOp::IntToPtr => {
                // No-op: pointers are already I64.
                // Emit a simple copy (add 0).
                let zero = self.fresh_value();
                let zero_inst = Instruction {
                    opcode: Opcode::Iconst {
                        ty: Type::I64,
                        imm: 0,
                    },
                    args: vec![],
                    results: vec![zero],
                };
                let add_inst = Instruction {
                    opcode: Opcode::Iadd,
                    args: vec![src, zero],
                    results: vec![dst],
                };
                return Ok(vec![zero_inst, add_inst]);
            }
            CastOp::Bitcast => {
                // Same-size reinterpret cast. For now emit as identity.
                let zero = self.fresh_value();
                let zero_inst = Instruction {
                    opcode: Opcode::Iconst {
                        ty: to,
                        imm: 0,
                    },
                    args: vec![],
                    results: vec![zero],
                };
                let add_inst = Instruction {
                    opcode: Opcode::Iadd,
                    args: vec![src, zero],
                    results: vec![dst],
                };
                return Ok(vec![zero_inst, add_inst]);
            }
        };

        Ok(vec![Instruction {
            opcode,
            args: vec![src],
            results: vec![dst],
        }])
    }

    // -----------------------------------------------------------------------
    // Memory operations
    // -----------------------------------------------------------------------

    fn translate_load(
        &mut self,
        ty: &Ty,
        ptr: &ValueId,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let lir_ty = translate_type(ty)?;
        let ptr_val = self.map_value(*ptr);
        let dst = self.map_result(results)?;

        Ok(vec![Instruction {
            opcode: Opcode::Load { ty: lir_ty },
            args: vec![ptr_val],
            results: vec![dst],
        }])
    }

    fn translate_store(
        &mut self,
        ptr: &ValueId,
        value: &ValueId,
    ) -> Result<Vec<Instruction>, AdapterError> {
        let ptr_val = self.map_value(*ptr);
        let val = self.map_value(*value);

        Ok(vec![Instruction {
            opcode: Opcode::Store,
            args: vec![val, ptr_val],
            results: vec![],
        }])
    }

    fn translate_alloc(
        &mut self,
        ty: &Ty,
        _count: &Option<ValueId>,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let _lir_ty = translate_type(ty)?;
        let dst = self.map_result(results)?;

        // Stack allocation: emit a StackAddr reference.
        // The actual stack slot allocation happens during frame lowering.
        // For now, use slot 0 as a placeholder.
        Ok(vec![Instruction {
            opcode: Opcode::StackAddr { slot: 0 },
            args: vec![],
            results: vec![dst],
        }])
    }

    // -----------------------------------------------------------------------
    // Control flow
    // -----------------------------------------------------------------------

    fn translate_br(
        &mut self,
        target: &BlockId,
        args: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let mut instrs = Vec::new();

        // Emit copies for block arguments -> block parameters.
        instrs.extend(self.resolve_block_args(*target, args)?);

        let dest = self.map_block(*target);
        instrs.push(Instruction {
            opcode: Opcode::Jump { dest },
            args: vec![],
            results: vec![],
        });

        Ok(instrs)
    }

    fn translate_condbr(
        &mut self,
        cond: &ValueId,
        then_target: &BlockId,
        then_args: &[ValueId],
        else_target: &BlockId,
        else_args: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let mut instrs = Vec::new();

        // Emit copies for then-branch block arguments.
        instrs.extend(self.resolve_block_args(*then_target, then_args)?);

        // Emit copies for else-branch block arguments.
        instrs.extend(self.resolve_block_args(*else_target, else_args)?);

        let cond_val = self.map_value(*cond);
        let then_dest = self.map_block(*then_target);
        let else_dest = self.map_block(*else_target);

        instrs.push(Instruction {
            opcode: Opcode::Brif {
                cond: cond_val,
                then_dest,
                else_dest,
            },
            args: vec![cond_val],
            results: vec![],
        });

        Ok(instrs)
    }

    fn translate_return(
        &mut self,
        values: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let args: Vec<Value> = values.iter().map(|vid| self.map_value(*vid)).collect();

        Ok(vec![Instruction {
            opcode: Opcode::Return,
            args,
            results: vec![],
        }])
    }

    fn translate_call(
        &mut self,
        _func: &FuncId,
        args: &[ValueId],
        _ret_ty: &[Ty],
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        // For MVP, calls are represented as Return-like instructions.
        // Full call lowering with ABI handling is done by the ISel.
        let arg_vals: Vec<Value> = args.iter().map(|vid| self.map_value(*vid)).collect();
        let result_vals = self.map_results(results);

        // Emit the call as a sequence of arg moves + call opcode.
        // The ISel handles the ABI details (register assignment, stack args).
        // For now, use Jump as a placeholder for the call target.
        // A proper Call opcode should be added to the internal LIR.
        Ok(vec![Instruction {
            opcode: Opcode::Return, // placeholder: real Call opcode needed
            args: arg_vals,
            results: result_vals,
        }])
    }

    // -----------------------------------------------------------------------
    // Phi / block parameters
    // -----------------------------------------------------------------------

    fn translate_phi(
        &mut self,
        _ty: &Ty,
        incoming: &[(BlockId, ValueId)],
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        // Phi nodes: tMIR uses block parameters for phis (the canonical form).
        // Explicit Phi instructions are redundant with block params but may appear.
        // Translate as a series of conditional moves (placeholder).
        let result = self.map_result(results)?;
        let args: Vec<Value> = incoming.iter().map(|(_, vid)| self.map_value(*vid)).collect();

        // If there are incoming values, use the first as default.
        if let Some(&first) = args.first() {
            Ok(vec![Instruction {
                opcode: Opcode::Iadd, // placeholder for phi/copy
                args: vec![first],
                results: vec![result],
            }])
        } else {
            Ok(vec![])
        }
    }

    // -----------------------------------------------------------------------
    // Constants
    // -----------------------------------------------------------------------

    fn translate_const(
        &mut self,
        ty: &Ty,
        value: i64,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let lir_ty = translate_type(ty)?;
        let dst = self.map_result(results)?;

        Ok(vec![Instruction {
            opcode: Opcode::Iconst {
                ty: lir_ty,
                imm: value,
            },
            args: vec![],
            results: vec![dst],
        }])
    }

    fn translate_fconst(
        &mut self,
        ty: &Ty,
        value: f64,
        results: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        let lir_ty = translate_type(ty)?;
        let dst = self.map_result(results)?;

        Ok(vec![Instruction {
            opcode: Opcode::Fconst {
                ty: lir_ty,
                imm: value,
            },
            args: vec![],
            results: vec![dst],
        }])
    }

    // -----------------------------------------------------------------------
    // Block argument resolution
    // -----------------------------------------------------------------------

    /// Emit copy instructions for block argument passing.
    ///
    /// tMIR uses block parameters for phi semantics: `Br { target, args }`
    /// passes `args` to the target block's `params`. The adapter emits
    /// Iadd-with-zero-arg copies (a single-arg Iadd acts as a move).
    fn resolve_block_args(
        &mut self,
        target: BlockId,
        args: &[ValueId],
    ) -> Result<Vec<Instruction>, AdapterError> {
        if args.is_empty() {
            return Ok(vec![]);
        }

        let mut copies = Vec::new();

        // Look up the target block's parameters from the tMIR function.
        let tmir_func = self
            .tmir_func
            .ok_or(AdapterError::UnknownBlock(target.0))?;
        let target_block = tmir_func
            .block(target)
            .ok_or(AdapterError::UnknownBlock(target.0))?;

        for (arg, (param_id, _param_ty)) in args.iter().zip(target_block.params.iter()) {
            let src = self.map_value(*arg);
            let dst = self.map_value(*param_id);
            copies.push(Instruction {
                opcode: Opcode::Iadd, // copy via single-arg add (placeholder for COPY pseudo)
                args: vec![src],
                results: vec![dst],
            });
        }

        Ok(copies)
    }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Translate a tMIR module into internal LIR functions with proof contexts.
///
/// Each function in the module is translated independently. The returned
/// vector pairs each internal `Function` with its `ProofContext`.
pub fn translate_module(
    module: &TmirModule,
) -> Result<Vec<(Function, ProofContext)>, AdapterError> {
    let mut results = Vec::new();
    for func in &module.functions {
        let (lir_func, proofs) = translate_function(func, &module.structs)?;
        results.push((lir_func, proofs));
    }
    Ok(results)
}

/// Translate a single tMIR function to internal LIR + proof context.
pub fn translate_function(
    func: &TmirFunction,
    structs: &[StructDef],
) -> Result<(Function, ProofContext), AdapterError> {
    let mut adapter = TmirAdapter::new(structs);
    adapter.translate(func)
}

/// Extract proof annotations from a tMIR instruction node.
///
/// Currently tMIR stubs do not carry explicit proof annotations.
/// This function is a placeholder for when the real tMIR crate
/// provides proof metadata. Returns an empty Vec for now.
pub fn extract_proofs(_node: &InstrNode) -> Vec<Proof> {
    // TODO: When tMIR stubs gain proof annotation fields,
    // extract NoOverflow, InBounds, NotNull, etc. from here.
    Vec::new()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use tmir_func::{Block as TmirBlockDef, Function as TmirFunc, Module};
    use tmir_types::{BlockId, FuncId, FuncTy, Ty, ValueId};

    /// Build a minimal tMIR module: fn add(a: i32, b: i32) -> i32 { a + b }
    fn build_add_module() -> Module {
        let func = TmirFunc {
            id: FuncId(0),
            name: "add".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32), Ty::Int(32)],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![
                    (ValueId(0), Ty::Int(32)), // param a
                    (ValueId(1), Ty::Int(32)), // param b
                ],
                body: vec![
                    InstrNode {
                        instr: Instr::BinOp {
                            op: BinOp::Add,
                            ty: Ty::Int(32),
                            lhs: ValueId(0),
                            rhs: ValueId(1),
                        },
                        results: vec![ValueId(2)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(2)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        Module {
            name: "test".to_string(),
            functions: vec![func],
            structs: vec![],
        }
    }

    #[test]
    fn test_translate_type_scalars() {
        assert_eq!(translate_type(&Ty::Bool).unwrap(), Type::B1);
        assert_eq!(translate_type(&Ty::Int(8)).unwrap(), Type::I8);
        assert_eq!(translate_type(&Ty::Int(16)).unwrap(), Type::I16);
        assert_eq!(translate_type(&Ty::Int(32)).unwrap(), Type::I32);
        assert_eq!(translate_type(&Ty::Int(64)).unwrap(), Type::I64);
        assert_eq!(translate_type(&Ty::Int(128)).unwrap(), Type::I128);
        assert_eq!(translate_type(&Ty::UInt(32)).unwrap(), Type::I32);
        assert_eq!(translate_type(&Ty::UInt(64)).unwrap(), Type::I64);
        assert_eq!(translate_type(&Ty::Float(32)).unwrap(), Type::F32);
        assert_eq!(translate_type(&Ty::Float(64)).unwrap(), Type::F64);
    }

    #[test]
    fn test_translate_type_ptr() {
        let ptr_ty = Ty::Ptr(Box::new(Ty::Int(32)));
        assert_eq!(translate_type(&ptr_ty).unwrap(), Type::I64);
    }

    #[test]
    fn test_translate_type_void_errors() {
        assert!(translate_type(&Ty::Void).is_err());
    }

    #[test]
    fn test_translate_type_unsupported() {
        let struct_ty = Ty::Struct(tmir_types::StructId(0));
        assert!(translate_type(&struct_ty).is_err());

        let array_ty = Ty::Array(Box::new(Ty::Int(32)), 10);
        assert!(translate_type(&array_ty).is_err());
    }

    #[test]
    fn test_translate_module_add() {
        let module = build_add_module();
        let results = translate_module(&module).unwrap();
        assert_eq!(results.len(), 1);

        let (func, _proofs) = &results[0];
        assert_eq!(func.name, "add");
        assert_eq!(func.signature.params, vec![Type::I32, Type::I32]);
        assert_eq!(func.signature.returns, vec![Type::I32]);
    }

    #[test]
    fn test_translate_function_blocks() {
        let module = build_add_module();
        let (func, _) = translate_function(&module.functions[0], &module.structs).unwrap();

        // Should have exactly 1 block.
        assert_eq!(func.blocks.len(), 1);

        // Entry block should have 2 params (a, b) and 2 instructions (add, return).
        let entry = &func.blocks[&func.entry_block];
        assert_eq!(entry.params.len(), 2);
        assert_eq!(entry.instructions.len(), 2);

        // First instruction: Iadd
        assert!(matches!(entry.instructions[0].opcode, Opcode::Iadd));
        assert_eq!(entry.instructions[0].args.len(), 2);
        assert_eq!(entry.instructions[0].results.len(), 1);

        // Second instruction: Return
        assert!(matches!(entry.instructions[1].opcode, Opcode::Return));
        assert_eq!(entry.instructions[1].args.len(), 1);
    }

    #[test]
    fn test_translate_const() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "const_42".to_string(),
            ty: FuncTy {
                params: vec![],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![],
                body: vec![
                    InstrNode {
                        instr: Instr::Const {
                            ty: Ty::Int(32),
                            value: 42,
                        },
                        results: vec![ValueId(0)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(0)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];
        assert_eq!(entry.instructions.len(), 2);

        match &entry.instructions[0].opcode {
            Opcode::Iconst { ty, imm } => {
                assert_eq!(*ty, Type::I32);
                assert_eq!(*imm, 42);
            }
            other => panic!("expected Iconst, got {:?}", other),
        }
    }

    #[test]
    fn test_translate_fconst() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "fconst".to_string(),
            ty: FuncTy {
                params: vec![],
                returns: vec![Ty::Float(64)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![],
                body: vec![
                    InstrNode {
                        instr: Instr::FConst {
                            ty: Ty::Float(64),
                            value: 3.14,
                        },
                        results: vec![ValueId(0)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(0)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        match &entry.instructions[0].opcode {
            Opcode::Fconst { ty, imm } => {
                assert_eq!(*ty, Type::F64);
                assert!((imm - 3.14).abs() < f64::EPSILON);
            }
            other => panic!("expected Fconst, got {:?}", other),
        }
    }

    #[test]
    fn test_translate_comparison() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "cmp_lt".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32), Ty::Int(32)],
                returns: vec![Ty::Bool],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![
                    (ValueId(0), Ty::Int(32)),
                    (ValueId(1), Ty::Int(32)),
                ],
                body: vec![
                    InstrNode {
                        instr: Instr::Cmp {
                            op: CmpOp::Slt,
                            ty: Ty::Int(32),
                            lhs: ValueId(0),
                            rhs: ValueId(1),
                        },
                        results: vec![ValueId(2)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(2)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        match &entry.instructions[0].opcode {
            Opcode::Icmp { cond } => {
                assert_eq!(*cond, IntCC::SignedLessThan);
            }
            other => panic!("expected Icmp, got {:?}", other),
        }
    }

    #[test]
    fn test_translate_float_comparison() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "fcmp_eq".to_string(),
            ty: FuncTy {
                params: vec![Ty::Float(64), Ty::Float(64)],
                returns: vec![Ty::Bool],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![
                    (ValueId(0), Ty::Float(64)),
                    (ValueId(1), Ty::Float(64)),
                ],
                body: vec![
                    InstrNode {
                        instr: Instr::Cmp {
                            op: CmpOp::FOeq,
                            ty: Ty::Float(64),
                            lhs: ValueId(0),
                            rhs: ValueId(1),
                        },
                        results: vec![ValueId(2)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(2)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        match &entry.instructions[0].opcode {
            Opcode::Fcmp { cond } => {
                assert_eq!(*cond, FloatCC::Equal);
            }
            other => panic!("expected Fcmp, got {:?}", other),
        }
    }

    #[test]
    fn test_translate_cast_sext() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "sext".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32)],
                returns: vec![Ty::Int(64)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![(ValueId(0), Ty::Int(32))],
                body: vec![
                    InstrNode {
                        instr: Instr::Cast {
                            op: CastOp::SExt,
                            src_ty: Ty::Int(32),
                            dst_ty: Ty::Int(64),
                            operand: ValueId(0),
                        },
                        results: vec![ValueId(1)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(1)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        match &entry.instructions[0].opcode {
            Opcode::Sextend { from_ty, to_ty } => {
                assert_eq!(*from_ty, Type::I32);
                assert_eq!(*to_ty, Type::I64);
            }
            other => panic!("expected Sextend, got {:?}", other),
        }
    }

    #[test]
    fn test_translate_load_store() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "load_store".to_string(),
            ty: FuncTy {
                params: vec![Ty::Ptr(Box::new(Ty::Int(32)))],
                returns: vec![],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![(ValueId(0), Ty::Ptr(Box::new(Ty::Int(32))))],
                body: vec![
                    InstrNode {
                        instr: Instr::Load {
                            ty: Ty::Int(32),
                            ptr: ValueId(0),
                        },
                        results: vec![ValueId(1)],
                    },
                    InstrNode {
                        instr: Instr::Store {
                            ty: Ty::Int(32),
                            ptr: ValueId(0),
                            value: ValueId(1),
                        },
                        results: vec![],
                    },
                    InstrNode {
                        instr: Instr::Return { values: vec![] },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        // Load
        match &entry.instructions[0].opcode {
            Opcode::Load { ty } => assert_eq!(*ty, Type::I32),
            other => panic!("expected Load, got {:?}", other),
        }

        // Store
        assert!(matches!(entry.instructions[1].opcode, Opcode::Store));
    }

    #[test]
    fn test_translate_unop_neg() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "neg".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32)],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![(ValueId(0), Ty::Int(32))],
                body: vec![
                    InstrNode {
                        instr: Instr::UnOp {
                            op: UnOp::Neg,
                            ty: Ty::Int(32),
                            operand: ValueId(0),
                        },
                        results: vec![ValueId(1)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(1)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        // Neg is lowered as: const 0, sub(0, operand), then return
        assert_eq!(entry.instructions.len(), 3); // iconst(0), isub, return
        assert!(matches!(
            entry.instructions[0].opcode,
            Opcode::Iconst { ty: Type::I32, imm: 0 }
        ));
        assert!(matches!(entry.instructions[1].opcode, Opcode::Isub));
    }

    #[test]
    fn test_translate_unop_not() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "not".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32)],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![(ValueId(0), Ty::Int(32))],
                body: vec![
                    InstrNode {
                        instr: Instr::UnOp {
                            op: UnOp::Not,
                            ty: Ty::Int(32),
                            operand: ValueId(0),
                        },
                        results: vec![ValueId(1)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(1)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        // Not is lowered as: iconst(-1), bxor(operand, -1)
        assert!(matches!(
            entry.instructions[0].opcode,
            Opcode::Iconst { imm: -1, .. }
        ));
        assert!(matches!(entry.instructions[1].opcode, Opcode::Bxor));
    }

    #[test]
    fn test_translate_remainder() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "srem".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32), Ty::Int(32)],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![
                    (ValueId(0), Ty::Int(32)),
                    (ValueId(1), Ty::Int(32)),
                ],
                body: vec![
                    InstrNode {
                        instr: Instr::BinOp {
                            op: BinOp::SRem,
                            ty: Ty::Int(32),
                            lhs: ValueId(0),
                            rhs: ValueId(1),
                        },
                        results: vec![ValueId(2)],
                    },
                    InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(2)],
                        },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        // SRem lowers to: sdiv, imul, isub, return = 4 instructions
        assert_eq!(entry.instructions.len(), 4);
        assert!(matches!(entry.instructions[0].opcode, Opcode::Sdiv));
        assert!(matches!(entry.instructions[1].opcode, Opcode::Imul));
        assert!(matches!(entry.instructions[2].opcode, Opcode::Isub));
        assert!(matches!(entry.instructions[3].opcode, Opcode::Return));
    }

    #[test]
    fn test_translate_branch_with_args() {
        // Two blocks: entry branches to loop_header with an argument.
        let func = TmirFunc {
            id: FuncId(0),
            name: "branch_args".to_string(),
            ty: FuncTy {
                params: vec![Ty::Int(32)],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![
                TmirBlockDef {
                    id: BlockId(0),
                    params: vec![(ValueId(0), Ty::Int(32))],
                    body: vec![InstrNode {
                        instr: Instr::Br {
                            target: BlockId(1),
                            args: vec![ValueId(0)],
                        },
                        results: vec![],
                    }],
                },
                TmirBlockDef {
                    id: BlockId(1),
                    params: vec![(ValueId(1), Ty::Int(32))],
                    body: vec![InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(1)],
                        },
                        results: vec![],
                    }],
                },
            ],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        assert_eq!(lir_func.blocks.len(), 2);

        // Entry block should have a copy + jump.
        let entry = &lir_func.blocks[&lir_func.entry_block];
        assert_eq!(entry.instructions.len(), 2); // copy + jump

        // First is a copy (Iadd placeholder).
        assert!(matches!(entry.instructions[0].opcode, Opcode::Iadd));

        // Second is the jump.
        assert!(matches!(entry.instructions[1].opcode, Opcode::Jump { .. }));
    }

    #[test]
    fn test_translate_conditional_branch() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "condbr".to_string(),
            ty: FuncTy {
                params: vec![Ty::Bool, Ty::Int(32), Ty::Int(32)],
                returns: vec![Ty::Int(32)],
            },
            entry: BlockId(0),
            blocks: vec![
                TmirBlockDef {
                    id: BlockId(0),
                    params: vec![
                        (ValueId(0), Ty::Bool),
                        (ValueId(1), Ty::Int(32)),
                        (ValueId(2), Ty::Int(32)),
                    ],
                    body: vec![InstrNode {
                        instr: Instr::CondBr {
                            cond: ValueId(0),
                            then_target: BlockId(1),
                            then_args: vec![],
                            else_target: BlockId(2),
                            else_args: vec![],
                        },
                        results: vec![],
                    }],
                },
                TmirBlockDef {
                    id: BlockId(1),
                    params: vec![],
                    body: vec![InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(1)],
                        },
                        results: vec![],
                    }],
                },
                TmirBlockDef {
                    id: BlockId(2),
                    params: vec![],
                    body: vec![InstrNode {
                        instr: Instr::Return {
                            values: vec![ValueId(2)],
                        },
                        results: vec![],
                    }],
                },
            ],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        assert_eq!(lir_func.blocks.len(), 3);

        let entry = &lir_func.blocks[&lir_func.entry_block];
        // Should have 1 instruction: brif (no block args to copy)
        assert_eq!(entry.instructions.len(), 1);
        assert!(matches!(entry.instructions[0].opcode, Opcode::Brif { .. }));
    }

    #[test]
    fn test_translate_all_binop_variants() {
        // Test that all BinOp variants translate without error.
        let binops = vec![
            (BinOp::Add, Ty::Int(32)),
            (BinOp::Sub, Ty::Int(32)),
            (BinOp::Mul, Ty::Int(32)),
            (BinOp::SDiv, Ty::Int(32)),
            (BinOp::UDiv, Ty::UInt(32)),
            (BinOp::SRem, Ty::Int(32)),
            (BinOp::URem, Ty::UInt(32)),
            (BinOp::And, Ty::Int(32)),
            (BinOp::Or, Ty::Int(32)),
            (BinOp::Xor, Ty::Int(32)),
            (BinOp::Shl, Ty::Int(32)),
            (BinOp::AShr, Ty::Int(32)),
            (BinOp::LShr, Ty::UInt(32)),
            (BinOp::FAdd, Ty::Float(64)),
            (BinOp::FSub, Ty::Float(64)),
            (BinOp::FMul, Ty::Float(64)),
            (BinOp::FDiv, Ty::Float(64)),
        ];

        for (op, ty) in binops {
            let func = TmirFunc {
                id: FuncId(0),
                name: format!("binop_{:?}", op),
                ty: FuncTy {
                    params: vec![ty.clone(), ty.clone()],
                    returns: vec![ty.clone()],
                },
                entry: BlockId(0),
                blocks: vec![TmirBlockDef {
                    id: BlockId(0),
                    params: vec![
                        (ValueId(0), ty.clone()),
                        (ValueId(1), ty.clone()),
                    ],
                    body: vec![
                        InstrNode {
                            instr: Instr::BinOp {
                                op,
                                ty: ty.clone(),
                                lhs: ValueId(0),
                                rhs: ValueId(1),
                            },
                            results: vec![ValueId(2)],
                        },
                        InstrNode {
                            instr: Instr::Return {
                                values: vec![ValueId(2)],
                            },
                            results: vec![],
                        },
                    ],
                }],
            };

            let result = translate_function(&func, &[]);
            assert!(
                result.is_ok(),
                "BinOp::{:?} translation failed: {:?}",
                op,
                result.err()
            );
        }
    }

    #[test]
    fn test_translate_all_int_cmp_variants() {
        let cmp_ops = vec![
            CmpOp::Eq,
            CmpOp::Ne,
            CmpOp::Slt,
            CmpOp::Sle,
            CmpOp::Sgt,
            CmpOp::Sge,
            CmpOp::Ult,
            CmpOp::Ule,
            CmpOp::Ugt,
            CmpOp::Uge,
        ];

        for op in cmp_ops {
            let func = TmirFunc {
                id: FuncId(0),
                name: format!("cmp_{:?}", op),
                ty: FuncTy {
                    params: vec![Ty::Int(32), Ty::Int(32)],
                    returns: vec![Ty::Bool],
                },
                entry: BlockId(0),
                blocks: vec![TmirBlockDef {
                    id: BlockId(0),
                    params: vec![
                        (ValueId(0), Ty::Int(32)),
                        (ValueId(1), Ty::Int(32)),
                    ],
                    body: vec![
                        InstrNode {
                            instr: Instr::Cmp {
                                op,
                                ty: Ty::Int(32),
                                lhs: ValueId(0),
                                rhs: ValueId(1),
                            },
                            results: vec![ValueId(2)],
                        },
                        InstrNode {
                            instr: Instr::Return {
                                values: vec![ValueId(2)],
                            },
                            results: vec![],
                        },
                    ],
                }],
            };

            let result = translate_function(&func, &[]);
            assert!(
                result.is_ok(),
                "CmpOp::{:?} translation failed: {:?}",
                op,
                result.err()
            );
        }
    }

    #[test]
    fn test_translate_all_float_cmp_variants() {
        let cmp_ops = vec![
            CmpOp::FOeq,
            CmpOp::FOne,
            CmpOp::FOlt,
            CmpOp::FOle,
            CmpOp::FOgt,
            CmpOp::FOge,
            CmpOp::FUeq,
            CmpOp::FUne,
            CmpOp::FUlt,
            CmpOp::FUle,
            CmpOp::FUgt,
            CmpOp::FUge,
        ];

        for op in cmp_ops {
            let func = TmirFunc {
                id: FuncId(0),
                name: format!("fcmp_{:?}", op),
                ty: FuncTy {
                    params: vec![Ty::Float(64), Ty::Float(64)],
                    returns: vec![Ty::Bool],
                },
                entry: BlockId(0),
                blocks: vec![TmirBlockDef {
                    id: BlockId(0),
                    params: vec![
                        (ValueId(0), Ty::Float(64)),
                        (ValueId(1), Ty::Float(64)),
                    ],
                    body: vec![
                        InstrNode {
                            instr: Instr::Cmp {
                                op,
                                ty: Ty::Float(64),
                                lhs: ValueId(0),
                                rhs: ValueId(1),
                            },
                            results: vec![ValueId(2)],
                        },
                        InstrNode {
                            instr: Instr::Return {
                                values: vec![ValueId(2)],
                            },
                            results: vec![],
                        },
                    ],
                }],
            };

            let result = translate_function(&func, &[]);
            assert!(
                result.is_ok(),
                "CmpOp::{:?} translation failed: {:?}",
                op,
                result.err()
            );
        }
    }

    #[test]
    fn test_proof_context_queries() {
        let mut ctx = ProofContext::default();

        let v0 = Value(0);
        let v1 = Value(1);

        ctx.value_proofs.insert(
            v0,
            vec![Proof::NoOverflow { signed: true }],
        );
        ctx.value_proofs.insert(
            v1,
            vec![
                Proof::InRange { lo: 0, hi: 255 },
                Proof::NotNull { ptr: ValueId(10) },
            ],
        );

        assert!(ctx.has_no_overflow(&v0));
        assert!(!ctx.has_no_overflow(&v1));

        assert!(ctx.has_not_null(&v1));
        assert!(!ctx.has_not_null(&v0));

        assert_eq!(ctx.get_range(&v1), Some((0, 255)));
        assert_eq!(ctx.get_range(&v0), None);
    }

    #[test]
    fn test_translate_nop() {
        let func = TmirFunc {
            id: FuncId(0),
            name: "with_nop".to_string(),
            ty: FuncTy {
                params: vec![],
                returns: vec![],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![],
                body: vec![
                    InstrNode {
                        instr: Instr::Nop,
                        results: vec![],
                    },
                    InstrNode {
                        instr: Instr::Return { values: vec![] },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];
        // Nop produces no instructions, so only the Return remains.
        assert_eq!(entry.instructions.len(), 1);
        assert!(matches!(entry.instructions[0].opcode, Opcode::Return));
    }

    #[test]
    fn test_extract_proofs_placeholder() {
        let node = InstrNode {
            instr: Instr::BinOp {
                op: BinOp::Add,
                ty: Ty::Int(32),
                lhs: ValueId(0),
                rhs: ValueId(1),
            },
            results: vec![ValueId(2)],
        };
        let proofs = extract_proofs(&node);
        assert!(proofs.is_empty()); // Stubs don't carry proofs yet.
    }

    #[test]
    fn test_translate_ownership_ops() {
        // Borrow/BorrowMut should produce a copy; EndBorrow/Retain/Release should be no-ops.
        let func = TmirFunc {
            id: FuncId(0),
            name: "ownership".to_string(),
            ty: FuncTy {
                params: vec![Ty::Ptr(Box::new(Ty::Int(32)))],
                returns: vec![],
            },
            entry: BlockId(0),
            blocks: vec![TmirBlockDef {
                id: BlockId(0),
                params: vec![(ValueId(0), Ty::Ptr(Box::new(Ty::Int(32))))],
                body: vec![
                    InstrNode {
                        instr: Instr::Borrow {
                            ty: Ty::Ptr(Box::new(Ty::Int(32))),
                            value: ValueId(0),
                        },
                        results: vec![ValueId(1)],
                    },
                    InstrNode {
                        instr: Instr::EndBorrow {
                            borrow: ValueId(1),
                        },
                        results: vec![],
                    },
                    InstrNode {
                        instr: Instr::Retain {
                            value: ValueId(0),
                        },
                        results: vec![],
                    },
                    InstrNode {
                        instr: Instr::Release {
                            value: ValueId(0),
                        },
                        results: vec![],
                    },
                    InstrNode {
                        instr: Instr::Return { values: vec![] },
                        results: vec![],
                    },
                ],
            }],
        };

        let (lir_func, _) = translate_function(&func, &[]).unwrap();
        let entry = &lir_func.blocks[&lir_func.entry_block];

        // Borrow -> 1 copy instruction (Iadd placeholder)
        // EndBorrow, Retain, Release -> 0 instructions each
        // Return -> 1 instruction
        // Total: 2 instructions
        assert_eq!(entry.instructions.len(), 2);
    }

    #[test]
    fn test_translate_multiple_functions() {
        let module = Module {
            name: "multi".to_string(),
            functions: vec![
                TmirFunc {
                    id: FuncId(0),
                    name: "foo".to_string(),
                    ty: FuncTy {
                        params: vec![Ty::Int(32)],
                        returns: vec![Ty::Int(32)],
                    },
                    entry: BlockId(0),
                    blocks: vec![TmirBlockDef {
                        id: BlockId(0),
                        params: vec![(ValueId(0), Ty::Int(32))],
                        body: vec![InstrNode {
                            instr: Instr::Return {
                                values: vec![ValueId(0)],
                            },
                            results: vec![],
                        }],
                    }],
                },
                TmirFunc {
                    id: FuncId(1),
                    name: "bar".to_string(),
                    ty: FuncTy {
                        params: vec![Ty::Float(64)],
                        returns: vec![Ty::Float(64)],
                    },
                    entry: BlockId(0),
                    blocks: vec![TmirBlockDef {
                        id: BlockId(0),
                        params: vec![(ValueId(0), Ty::Float(64))],
                        body: vec![InstrNode {
                            instr: Instr::Return {
                                values: vec![ValueId(0)],
                            },
                            results: vec![],
                        }],
                    }],
                },
            ],
            structs: vec![],
        };

        let results = translate_module(&module).unwrap();
        assert_eq!(results.len(), 2);
        assert_eq!(results[0].0.name, "foo");
        assert_eq!(results[1].0.name, "bar");
    }
}
