#!/usr/bin/env bash
# Copyright 2026 Dropbox, Inc.
# Author: Andrew Yates <ayates@dropbox.com>
# Licensed under the Apache License, Version 2.0

# fix_lfs_offline.sh - Configure Git LFS for offline-friendly operation
#
# When cd-ing into a repo with LFS hooks, shell prompts that run `git status`
# can hang if the network is unavailable. This script configures LFS to:
# 1. Skip automatic file downloads (smudge --skip)
# 2. Use non-blocking hooks with timeouts
#
# Usage:
#   ./ai_template_scripts/fix_lfs_offline.sh [OPTIONS] [REPO_PATH]
#
# After running, manually use:
#   git lfs pull       # Download LFS files when online
#   git lfs push --all # Upload before pushing

set -euo pipefail

usage() {
    echo "Usage: $0 [OPTIONS] [REPO_PATH]"
    echo ""
    echo "Configure Git LFS for offline-friendly operation."
    echo ""
    echo "When entering a repo with LFS hooks, shell prompts that run 'git status'"
    echo "can hang if the network is unavailable. This script configures LFS to"
    echo "skip automatic file downloads and use non-blocking hooks with timeouts."
    echo ""
    echo "Arguments:"
    echo "  REPO_PATH    Path to git repository (default: current directory)"
    echo ""
    echo "Options:"
    echo "  -h, --help   Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                        # Configure current directory"
    echo "  $0 /path/to/repo          # Configure specific repo"
    echo ""
    echo "After running, manually use:"
    echo "  git lfs pull       # Download LFS files when online"
    echo "  git lfs push --all # Upload before pushing"
    echo ""
    echo "To revert to default LFS behavior:"
    echo "  git lfs install --force"
    exit 0
}

case "${1:-}" in
    -h|--help) usage ;;
    -*)
        echo "Error: Unknown option: $1" >&2
        echo "Use --help for usage information." >&2
        exit 1
        ;;
esac

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

# Determine repo path
REPO_PATH="${1:-.}"
cd "$REPO_PATH" || err "Cannot cd to $REPO_PATH"

# Verify this is a git repo
if ! git rev-parse --git-dir &>/dev/null; then
    err "Not a git repository: $REPO_PATH"
fi

GIT_DIR="$(git rev-parse --git-dir)"

# Check if LFS is installed
if ! command -v git-lfs &>/dev/null; then
    warn "Git LFS is not installed. Installing hooks anyway for future use."
fi

# Check if repo uses LFS
if ! git lfs ls-files &>/dev/null 2>&1 && [[ ! -f ".gitattributes" ]]; then
    warn "Repo doesn't appear to use LFS. Applying config anyway."
fi

info "Configuring LFS for offline operation..."

# Configure LFS to skip automatic downloads
git config lfs.fetchexclude "*"
git config lfs.concurrenttransfers 1
git config filter.lfs.smudge "git-lfs smudge --skip -- %f"
git config filter.lfs.process "git-lfs filter-process --skip"
git config filter.lfs.clean "git-lfs clean -- %f"
git config filter.lfs.required true

info "LFS config updated (smudge --skip enabled)"

# Create non-blocking hooks
HOOKS_DIR="$GIT_DIR/hooks"
mkdir -p "$HOOKS_DIR"

# Non-blocking hook for post-checkout, post-commit, post-merge
for hook in post-checkout post-commit post-merge; do
    HOOK_FILE="$HOOKS_DIR/$hook"
    if [[ -f "$HOOK_FILE" ]] && ! grep -q "Non-blocking LFS hook" "$HOOK_FILE"; then
        warn "Existing $hook hook found, backing up to ${hook}.bak"
        mv "$HOOK_FILE" "${HOOK_FILE}.bak"
    fi

    cat > "$HOOK_FILE" << 'HOOK_EOF'
#!/bin/sh
# Non-blocking LFS hook - times out after 2 seconds to prevent shell hang
# Generated by fix_lfs_offline.sh
(timeout 2 git lfs $0 "$@" 2>/dev/null || true) &
HOOK_EOF

    # Fix the hook name reference (post-checkout calls "git lfs post-checkout")
    sed -i.tmp "s|\$0|${hook}|g" "$HOOK_FILE" && rm -f "${HOOK_FILE}.tmp"
    chmod +x "$HOOK_FILE"
    info "Created non-blocking $hook hook"
done

# Pre-push hook with timeout (needs to be blocking but graceful)
PREPUSH_HOOK="$HOOKS_DIR/pre-push"
if [[ -f "$PREPUSH_HOOK" ]] && ! grep -q "LFS pre-push with timeout" "$PREPUSH_HOOK"; then
    warn "Existing pre-push hook found, backing up to pre-push.bak"
    mv "$PREPUSH_HOOK" "${PREPUSH_HOOK}.bak"
fi

cat > "$PREPUSH_HOOK" << 'HOOK_EOF'
#!/bin/sh
# LFS pre-push with timeout - fails gracefully if offline
# Generated by fix_lfs_offline.sh
if ! timeout 10 git lfs pre-push "$@" 2>/dev/null; then
    echo "Warning: LFS pre-push skipped (offline or timeout)" >&2
fi
exit 0
HOOK_EOF

chmod +x "$PREPUSH_HOOK"
info "Created graceful pre-push hook"

echo ""
info "LFS offline configuration complete!"
echo ""
echo "Usage:"
echo "  git lfs pull          # Download LFS files when online"
echo "  git lfs push --all    # Upload LFS files before pushing"
echo ""
echo "To revert to default LFS behavior:"
echo "  git lfs install --force"
