#!/usr/bin/env python3
"""Generate SKILLS.md index from skill files in .claude/commands/.

Copyright 2026 Dropbox, Inc.
Author: Andrew Yates <ayates@dropbox.com>
License: Apache-2.0
"""

from pathlib import Path


def parse_skill_file(filepath: Path) -> dict | None:
    """Parse a skill markdown file and extract metadata.

    Returns dict with keys: name, description, triggers, filename
    Returns None if file doesn't look like a skill.
    """
    content = filepath.read_text()
    lines = content.split("\n")

    # Get skill name from first header
    name = None
    for line in lines:
        if line.startswith("# "):
            name = line[2:].strip()
            break

    if not name:
        return None

    # Get description (first non-empty line after header)
    description = ""
    found_header = False
    for line in lines:
        if line.startswith("# "):
            found_header = True
            continue
        if found_header and line.strip():
            # Skip lines that look like parameters or examples
            if line.startswith(("Provide:", "Example:")):
                continue
            description = line.strip()
            break

    # Extract "You Might Say" triggers
    triggers = []
    in_triggers_section = False
    for line in lines:
        if "## You Might Say" in line:
            in_triggers_section = True
            continue
        if in_triggers_section:
            if line.startswith("##"):
                break
            if line.startswith("- "):
                # Clean up the trigger text
                trigger = line[2:].strip().strip('"').strip("'")
                triggers.append(trigger)

    return {
        "name": name,
        "filename": filepath.stem,
        "description": description,
        "triggers": triggers,
    }


def categorize_skills(skills: list[dict]) -> dict[str, list[dict]]:
    """Group skills into categories based on filename patterns."""
    categories: dict[str, list[dict]] = {
        "Session Workflow": [],
        "Task Lifecycle": [],
        "Communication": [],
        "MANAGER Tools": [],
        "Utilities": [],
    }

    workflow_skills = {"w-start", "w-commit", "handoff"}
    lifecycle_skills = {"claim", "complete", "blocked", "verify"}
    communication_skills = {"crossmsg", "news", "news-post", "mail", "vote"}
    manager_skills = {"m-cycle", "directive", "m-workers", "m-status", "blockers"}

    for skill in skills:
        filename = skill["filename"]
        if filename in workflow_skills:
            categories["Session Workflow"].append(skill)
        elif filename in lifecycle_skills:
            categories["Task Lifecycle"].append(skill)
        elif filename in communication_skills:
            categories["Communication"].append(skill)
        elif filename in manager_skills:
            categories["MANAGER Tools"].append(skill)
        else:
            categories["Utilities"].append(skill)

    return categories


def generate_skills_md(categories: dict[str, list[dict]]) -> str:
    """Generate SKILLS.md content from categorized skills."""
    lines = [
        "# Skill Index",
        "",
        "Auto-generated index of all skills in `.claude/commands/`.",
        "",
        "---",
        "",
    ]

    # Summary table
    lines.append("## Quick Reference")
    lines.append("")
    lines.append("| Skill | Description |")
    lines.append("|-------|-------------|")

    for skills in categories.values():
        for skill in sorted(skills, key=lambda s: s["filename"]):
            desc = (
                skill["description"][:60] + "..."
                if len(skill["description"]) > 60
                else skill["description"]
            )
            lines.append(f"| `/{skill['filename']}` | {desc} |")

    lines.append("")

    # Detailed sections by category
    for category, skills in categories.items():
        if not skills:
            continue

        lines.append(f"## {category}")
        lines.append("")

        for skill in sorted(skills, key=lambda s: s["filename"]):
            lines.append(f"### `/{skill['filename']}` - {skill['name']}")
            lines.append("")
            lines.append(skill["description"])
            lines.append("")

            if skill["triggers"]:
                lines.append("**You might say:**")
                lines.extend(f"- {trigger}" for trigger in skill["triggers"][:3])
                lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by `./ai_template_scripts/generate_skill_index.py`*")
    lines.append("")

    return "\n".join(lines)


def main():
    """Generate SKILLS.md from skill files."""
    commands_dir = Path(".claude/commands")

    if not commands_dir.exists():
        print(f"Error: {commands_dir} not found")
        return 1

    # Parse all skill files
    skills = []
    for filepath in sorted(commands_dir.glob("*.md")):
        skill = parse_skill_file(filepath)
        if skill:
            skills.append(skill)
            print(f"  Parsed: {filepath.stem} - {skill['name']}")

    if not skills:
        print("No skills found")
        return 1

    print(f"\nFound {len(skills)} skills")

    # Categorize and generate
    categories = categorize_skills(skills)
    content = generate_skills_md(categories)

    # Write output
    output_path = Path(".claude/SKILLS.md")
    output_path.write_text(content)
    print(f"\nGenerated: {output_path}")

    return 0


if __name__ == "__main__":
    exit(main())
